spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: maoxin
    url: jdbc:mysql://localhost/wechat-order?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  servlet:
    context-path: /sell
  tomcat:
    accesslog:
      encoding: UTF-8

executor:



wechat:
  mp-app-id: wx758f78f4279aed99
  mp-app-secret: a0c984a3b80683d39f68c3fb1d337e46

alipay:
  open-api-domain: https://openapi.alipaydev.com/gateway.do
  mcloud-api-domain: http://mcloudmonitor.com/gateway.do
  pid: 2016092700607046
  appid: 2016092700607046
  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCO/jKPOwkC2Jb90s+EUvqOxRArmwGgzlrelZrgaWnyafF/dfN8UVipw0N0YnBZSHlYm1UYNS/j3rb3VWZMG+jXujUo8UhfX6v3hym1kB9wCppOX2AILlxLjeK6JDdM6sfAeQjRL5JOuDaerG5Td+73Tf+I/095zXUpOfXRm97qjoq1wi12nJZF4Rh7GpHYRWATkCd6zW5Ajg0etHGDhbFEGnORFMaHAlZUDpn90HzH0Eel1RMHrAYongdx3p6xhPBC7oNpXff20/pT7wEMHiJpKAx9uZbUs5kuEoSeQzoSaZwTMSDzOJaXqC/snYAHOeCAOxJKPhVfeIFsc54KiJXfAgMBAAECggEAIiD1vE3g1rcPQsHAGdscRlsugtnaR6E4+wtGDe3bBarXow5p8PARc2NRhEPCgOzVWZqpcr+vEHolvV66rcuzhVnCOmVsWqchClFOWTFu73T4Y2BMMWevS7EvvjHKqScYSg4ZVqQ+DV/WWYTaSD3F4WzSYsZdF7s8DXzx+Pd0+xJytgh81LiwnDsdB96V5eejHp97NXLxLncon4BGHnS9099DdN5QBgTIPlfX1dg3BuRI9Qon8tkHMYFBFJgWPd8GdSSAKLpicL0V1BrSmyeBop12p8QBX8v5LMkjqeM5Mw9a5+sCoIzWh5LsIVWpdABXN7c83fhILIxVHV/eQNFsQQKBgQDScZyQ65kf/SWlesMEAW3SRZ0GqesZALEfiDQEIiX0AoyzQRCzrU93VDq+UkHYDfl6GhFmvRnHMFXj80X12CM4au1pS1seSpFF8u6jvoCsC3LgU2vkZHNV/vn+teJ36bvS8hsjOxjzmOtP4K/i22qXdl0jyAEwPcflh51QUHaBDwKBgQCt8pdG5TL3ucL9YLZiMu0CdV21JNcYcUAnpPRngmMKZXF7PryrcX+TPPhibzsH2q5Qv5gfbWpP0XyQ/KEwZQey3Z5cHkv88KVy7WmnJdfo1Ed3KvKEx7Cd591vCzDSB4tqznAgjb5vwxu9DSznznXXKWF5PddS98i8/br6aWP+MQKBgQCjMJDt3JT4tnDsGv+Baq5EAdGb6kYyNFQmFJPppKVzzEpZcxpFix71dS68icMfjO6qHe7ikb+ctEHWq77TvxDI3jpOja4SFlcDPDiMZ90WDSa/CFHBYZgC1t/8AgWlYW5STYZ30ost06aeYaljLS1CWPovFhi91RrfRkPalRrgRwKBgEloK/EOPoEOkrws+SrdxOmZsA8G2gMFoAZa9Y1NGBDGGKrjIenT/vua6lNYD3hUD+YhxMfWe9vtUv04r6llqWcRYYgMfRLkV1311PVl4gTuuK4QoMHqJ52rwOXguhyYdHyBXA5Q4wH1O5p/mejFVzOS0gDBWUI5MSyYgzS0Dy+xAoGAKT7akSd/QzVhZtIgry9kWTwTWeveKbJ8x1Xs5xVAp6vqrYuRkofSW7jU7/yh/popGD3TUl8qB2BOPbteJRlK/swEiZD/9eMZr90MEZqFlc62SbxnkD18RaKKraeIIZk3APoIRAjUnazVrNIQ9nwK6w2VCo6ufXWi+SXmx/edsDg=
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjv4yjzsJAtiW/dLPhFL6jsUQK5sBoM5a3pWa4Glp8mnxf3XzfFFYqcNDdGJwWUh5WJtVGDUv496291VmTBvo17o1KPFIX1+r94cptZAfcAqaTl9gCC5cS43iuiQ3TOrHwHkI0S+STrg2nqxuU3fu903/iP9Pec11KTn10Zve6o6KtcItdpyWReEYexqR2EVgE5Anes1uQI4NHrRxg4WxRBpzkRTGhwJWVA6Z/dB8x9BHpdUTB6wGKJ4Hcd6esYTwQu6DaV339tP6U+8BDB4iaSgMfbmW1LOZLhKEnkM6EmmcEzEg8ziWl6gv7J2ABznggDsSSj4VX3iBbHOeCoiV3wIDAQAB
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvTkWjulI66ofglB890YZWzNjfqXuCaY++tywMR2yG5Kujsmny5GT3nGOtY/E2zDrco7374CK34tg0XM67T3103aUBZaBMnqfwgehT4eQ3qU0xtcXPw0NAYNuY0nxTQnx4+a2Ql+EzNahCPGf4MJH4DmBDqEBUGOfXnr180/3Ry3JzlMIbYcOP7q+BU6i0WFvSRjBcBQF91KWd9vI2BTKYw5M8hzF5IFo66C39YemvZSWySgO8qM8io19UuzaeHRdreCNrlowTVD8wd5EGQ0gIAst93/VyxLs9KxEzd3tgAly0LlNaZNH3GSfzBK8x50EYQU/FDyr4KtyLXijBOJTvQIDAQAB
  sign-type: RSA2
  # 当面付最大查询次数和查询间隔（毫秒）
  max-query-retry: 5
  query-duration: 5000
  # 当面付最大撤销次数和撤销间隔（毫秒）
  max-cancel-retry: 3
  cancel-duration: 2000

  # 交易保障线程第一次调度延迟和调度间隔（秒）
  heartbeat-delay: 5
  heartbeat-duration: 900
  call-back: http://maoxin.napapp1.cc


project-url:
  wechat-mp-authorize: http://maoxin.natapp1.cc
