spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: maoxin
    url: jdbc:mysql://localhost/wechat-order?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  servlet:
    context-path: /sell

executor:



wechat:
  mp-app-id: wx758f78f4279aed99
  mp-app-secret: a0c984a3b80683d39f68c3fb1d337e46

project-url:
  wechat-mp-authorize: http://maoxin.natapp1.cc

